name: Validate

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - run: set -eu
      - run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build ktlintFormat
